# ==============================================================================
# GLOBAL CONFIGURATION & UI CONSTANTS
# ==============================================================================

# Floating window / header
WINDOW_TITLE_TEXT = "Buddy v1.0.0 Pre-Release"
WINDOW_TITLE_COLOR = "#6a737d"
WINDOW_TITLE_SIZE = 18
WINDOW_TITLE_WEIGHT = 600
WINDOW_HEADER_HEIGHT = 42
WINDOW_HEADER_PADDING_TOP = 8
WINDOW_HEADER_PADDING_RIGHT = 14
WINDOW_HEADER_PADDING_BOTTOM = 8
WINDOW_HEADER_PADDING_LEFT = 18
WINDOW_CLOSE_BUTTON_SIZE = 24
WINDOW_CLOSE_BUTTON_COLOR = "#777777"
WINDOW_CLOSE_BUTTON_HOVER_BG = "rgba(0, 0, 0, 0.08)"
WINDOW_CLOSE_BUTTON_HOVER_COLOR = "#222222"
WINDOW_CLOSE_BUTTON_FONT_SIZE = 14

# Sidebar Dimensions
SIDEBAR_COLLAPSED_WIDTH = 50
SIDEBAR_EXPANDED_WIDTH = 125
ICON_SIZE = 18
SIDEBAR_ANIM_MS = 170

# Version Control / Redo Limits
MAX_REDOS = 3

# UI Colors & Styling
PRIMARY_COLOR = "#2b81f2"
PRIMARY_COLOR_DARK = "#1c6ad9"
TEXT_COLOR_DARK = "#222222"
TEXT_COLOR_MUTED = "#8a8a8e"
TEXT_COLOR_SUBTITLE = "#555555"
HOVER_BG_COLOR = "rgba(0, 0, 0, 0.06)"
ACTIVE_BG_COLOR = "rgba(43, 127, 240, 0.12)"
CONTAINER_BG = "rgba(255, 255, 255, 0.85)"
SIDEBAR_BG = "rgba(248, 249, 251, 0.75)"
BORDER_COLOR = "rgba(0, 0, 0, 0.07)"
WINDOW_BG_TOP = "#fdfeff"
WINDOW_BG_MID = "#eaf3fd"
WINDOW_BG_BOTTOM = "#dceafc"
PAGE_BG_TOP = "#ffffff"
PAGE_BG_MID = "#f4f9ff"
PAGE_BG_BOTTOM = "#edf3ff"
CARD_TEXT_COLOR = "#1f2937"
CARD_TEXT_SIZE = 26
CARD_TEXT_WEIGHT = 700
CARD_SUBTITLE_COLOR = "#5f6b7a"
CARD_SUBTITLE_SIZE = 13
INPUT_BG = "#ffffff"
INPUT_BORDER = "rgba(0,0,0,0.06)"
CHAT_BUBBLE_USER = "#2b7ff0"
CHAT_BUBBLE_USER_TEXT = "#ffffff"
CHAT_BUBBLE_AGENT = "rgba(255, 255, 255, 0.9)"
CHAT_BUBBLE_AGENT_TEXT = "#222222"

# Window sizing — kept generous enough that nothing clips at min size
WINDOW_MIN_WIDTH = 380
WINDOW_MIN_HEIGHT = 450
WINDOW_DEFAULT_WIDTH = 500
WINDOW_DEFAULT_HEIGHT = 600

# Typography
GREETING_FONT_SIZE = 24
GREETING_COLOR = "#2b2b2b"
SUBTITLE_FONT_SIZE = 12

# Control sizing
SEND_BUTTON_SIZE = 36
SEND_BUTTON_RADIUS = 18
INPUT_CONTAINER_HEIGHT = 50
SIZE_GRIP_SIZE = 48